
server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/


spring:
  #  rabbitmq:
  #    addresses: 10.126.249.167
  #    username: admin
  #    password: 123456
  #    publisherConfirms: true
  #    publisherReturns: true
  application:
    name: order